/**
 * Labeled training corpus for the PRISM intent classifier.
 *
 * Each entry maps a natural-language query to one of the 17 intents the engine
 * can answer. Phrasings vary in length, formality, word order and vocabulary so
 * the model learns discriminative terms rather than memorising whole sentences.
 *
 * Corpus design notes:
 *  - Intent pairs that share vocabulary (revenue_by_product vs revenue_by_state,
 *    stock_level vs low_stock vs dead_stock, profit vs revenue_total) carry extra
 *    examples, so the distinguishing words appear often enough to be learned.
 *  - Indian-English business phrasing ("godown", "party", "lakh", "kitna") is
 *    included because that is how the actual users of this system speak.
 */

export const TRAINING_DATA = [
  // ── revenue_total ─────────────────────────────────────────────────────────
  ['what is our total revenue', 'revenue_total'],
  ['how much have we sold', 'revenue_total'],
  ['total sales figure', 'revenue_total'],
  ['show me overall turnover', 'revenue_total'],
  ['what is the total business done', 'revenue_total'],
  ['give me total sales value', 'revenue_total'],
  ['what is our gross sales value', 'revenue_total'],
  ['total booked revenue so far', 'revenue_total'],
  ['what is our topline', 'revenue_total'],
  ['revenue this month', 'revenue_total'],
  ['sales in the last 30 days', 'revenue_total'],
  ['total order value booked', 'revenue_total'],
  ['average order value', 'revenue_total'],
  ['how much revenue this year', 'revenue_total'],
  ['overall sales number please', 'revenue_total'],
  ['what was last week sales figure', 'revenue_total'],
  ['total turnover figure', 'revenue_total'],
  ['sum of all order values', 'revenue_total'],
  ['aggregate revenue number', 'revenue_total'],
  ['company wide sales total', 'revenue_total'],
  ['total revenue booked till date', 'revenue_total'],
  ['what is the gross sales amount', 'revenue_total'],
  ['how much business did we do', 'revenue_total'],
  ['show total sales value in rupees', 'revenue_total'],
  ['revenue generated this quarter', 'revenue_total'],
  ['our total billing amount', 'revenue_total'],
  ['what is combined sales revenue', 'revenue_total'],
  ['total sales realisation', 'revenue_total'],
  ['how much turnover yesterday', 'revenue_total'],
  ['net sales value overall', 'revenue_total'],
  ['what is the average ticket size', 'revenue_total'],
  ['total value of all orders combined', 'revenue_total'],
  ['sales revenue summary', 'revenue_total'],
  ['how much did the company sell', 'revenue_total'],
  ['revenue figure for today', 'revenue_total'],
  ['what is our sales run rate', 'revenue_total'],
  ['show me the topline number', 'revenue_total'],
  ['total value of goods sold', 'revenue_total'],
  ['overall business volume', 'revenue_total'],
  ['what is total sales this fortnight', 'revenue_total'],
  ['cumulative revenue amount', 'revenue_total'],
  ['how much have we billed overall', 'revenue_total'],
  ['sales performance total figure', 'revenue_total'],

  // ── revenue_by_product ────────────────────────────────────────────────────
  ['revenue by product', 'revenue_by_product'],
  ['which product sells the most', 'revenue_by_product'],
  ['best selling items', 'revenue_by_product'],
  ['top products by sales', 'revenue_by_product'],
  ['product wise sales breakdown', 'revenue_by_product'],
  ['show me sales per item', 'revenue_by_product'],
  ['which sku earns the most money', 'revenue_by_product'],
  ['highest grossing product', 'revenue_by_product'],
  ['product performance report', 'revenue_by_product'],
  ['how many units of each product sold', 'revenue_by_product'],
  ['sales split by product', 'revenue_by_product'],
  ['what are our top selling goods', 'revenue_by_product'],
  ['revenue contribution of each item', 'revenue_by_product'],
  ['which article is most popular', 'revenue_by_product'],
  ['ranking of products by turnover', 'revenue_by_product'],
  ['worst selling product', 'revenue_by_product'],
  ['product sales comparison', 'revenue_by_product'],
  ['item wise revenue chart', 'revenue_by_product'],
  ['which sku is the top performer', 'revenue_by_product'],
  ['sales figures for each product', 'revenue_by_product'],
  ['product mix analysis', 'revenue_by_product'],
  ['which goods bring most revenue', 'revenue_by_product'],
  ['break down sales by item name', 'revenue_by_product'],
  ['top 5 products by value', 'revenue_by_product'],
  ['revenue per sku', 'revenue_by_product'],
  ['which product line is strongest', 'revenue_by_product'],
  ['product category sales report', 'revenue_by_product'],
  ['what items are moving fastest', 'revenue_by_product'],
  ['show product wise numbers', 'revenue_by_product'],
  ['sales quantity by product', 'revenue_by_product'],
  ['which item has highest turnover', 'revenue_by_product'],
  ['compare products by sales value', 'revenue_by_product'],
  ['bestseller list', 'revenue_by_product'],
  ['product revenue ranking table', 'revenue_by_product'],
  ['which merchandise sells best', 'revenue_by_product'],
  ['item level sales analysis', 'revenue_by_product'],
  ['what product makes us most money', 'revenue_by_product'],
  ['sku performance breakdown', 'revenue_by_product'],
  ['units sold per item', 'revenue_by_product'],
  ['show me leading products', 'revenue_by_product'],
  ['which product contributes most revenue', 'revenue_by_product'],
  ['product wise turnover figures', 'revenue_by_product'],

  // ── revenue_by_state ──────────────────────────────────────────────────────
  ['revenue by state', 'revenue_by_state'],
  ['which region sells the most', 'revenue_by_state'],
  ['sales by territory', 'revenue_by_state'],
  ['state wise revenue breakdown', 'revenue_by_state'],
  ['geographic sales distribution', 'revenue_by_state'],
  ['top performing states', 'revenue_by_state'],
  ['how much business from each zone', 'revenue_by_state'],
  ['regional performance report', 'revenue_by_state'],
  ['sales per location', 'revenue_by_state'],
  ['which area gives most business', 'revenue_by_state'],
  ['revenue split across regions', 'revenue_by_state'],
  ['show me territory wise numbers', 'revenue_by_state'],
  ['state level sales figures', 'revenue_by_state'],
  ['geography wise turnover', 'revenue_by_state'],
  ['weakest region by sales', 'revenue_by_state'],
  ['area wise business summary', 'revenue_by_state'],
  ['which state is our biggest market', 'revenue_by_state'],
  ['zone wise sales report', 'revenue_by_state'],
  ['city wise revenue numbers', 'revenue_by_state'],
  ['sales distribution across states', 'revenue_by_state'],
  ['map of revenue by region', 'revenue_by_state'],
  ['which territory underperforms', 'revenue_by_state'],
  ['compare states by sales', 'revenue_by_state'],
  ['north versus south sales', 'revenue_by_state'],
  ['location wise business figures', 'revenue_by_state'],
  ['revenue from each state', 'revenue_by_state'],
  ['regional market share', 'revenue_by_state'],
  ['which zones need attention', 'revenue_by_state'],
  ['state wise turnover table', 'revenue_by_state'],
  ['show geographic breakdown of sales', 'revenue_by_state'],
  ['sales figures region wise', 'revenue_by_state'],
  ['top markets by geography', 'revenue_by_state'],
  ['which place generates most revenue', 'revenue_by_state'],
  ['district wise sales', 'revenue_by_state'],
  ['area performance comparison', 'revenue_by_state'],
  ['revenue concentration by region', 'revenue_by_state'],
  ['where are our sales coming from', 'revenue_by_state'],
  ['state contribution to revenue', 'revenue_by_state'],
  ['territory sales leaderboard', 'revenue_by_state'],
  ['which region is growing fastest', 'revenue_by_state'],

  // ── order_summary ─────────────────────────────────────────────────────────
  ['how many orders do we have', 'order_summary'],
  ['show me all pending orders', 'order_summary'],
  ['list the delivered orders', 'order_summary'],
  ['order status breakdown', 'order_summary'],
  ['how many bookings are open', 'order_summary'],
  ['what orders are shipped', 'order_summary'],
  ['count of cancelled orders', 'order_summary'],
  ['orders awaiting dispatch', 'order_summary'],
  ['give me the order list', 'order_summary'],
  ['how many orders processing right now', 'order_summary'],
  ['display recent orders', 'order_summary'],
  ['total number of orders placed', 'order_summary'],
  ['which orders are still pending', 'order_summary'],
  ['order pipeline overview', 'order_summary'],
  ['show partially delivered orders', 'order_summary'],
  ['orders booked this week', 'order_summary'],
  ['status of all bookings', 'order_summary'],
  ['how many consignments dispatched', 'order_summary'],
  ['order count by status', 'order_summary'],
  ['what is pending for delivery', 'order_summary'],
  ['show order register', 'order_summary'],
  ['orders ready for dispatch', 'order_summary'],
  ['how many deliveries completed', 'order_summary'],
  ['list orders placed today', 'order_summary'],
  ['open order book', 'order_summary'],
  ['which consignments are in transit', 'order_summary'],
  ['order fulfilment status', 'order_summary'],
  ['number of orders received', 'order_summary'],
  ['show me undelivered orders', 'order_summary'],
  ['orders in processing stage', 'order_summary'],
  ['how many orders got cancelled', 'order_summary'],
  ['pending dispatch list', 'order_summary'],
  ['order summary report', 'order_summary'],
  ['what bookings came in this month', 'order_summary'],
  ['show all order records', 'order_summary'],
  ['how many orders are complete', 'order_summary'],
  ['delivery status of orders', 'order_summary'],
  ['orders yet to be shipped', 'order_summary'],
  ['give me order statistics', 'order_summary'],
  ['how many purchase orders booked', 'order_summary'],

  // ── lead_summary ──────────────────────────────────────────────────────────
  ['how many leads do we have', 'lead_summary'],
  ['show me the lead pipeline', 'lead_summary'],
  ['list all prospects', 'lead_summary'],
  ['lead status breakdown', 'lead_summary'],
  ['how many enquiries came in', 'lead_summary'],
  ['converted leads count', 'lead_summary'],
  ['what is our conversion rate', 'lead_summary'],
  ['leads in negotiation stage', 'lead_summary'],
  ['open opportunities list', 'lead_summary'],
  ['how many prospects are lost', 'lead_summary'],
  ['pipeline value of leads', 'lead_summary'],
  ['show enquiries received', 'lead_summary'],
  ['leads by stage', 'lead_summary'],
  ['total prospect count', 'lead_summary'],
  ['which leads need follow up', 'lead_summary'],
  ['lead funnel report', 'lead_summary'],
  ['how many new enquiries this week', 'lead_summary'],
  ['qualified leads count', 'lead_summary'],
  ['what is in our sales funnel', 'lead_summary'],
  ['prospect conversion statistics', 'lead_summary'],
  ['leads that were won', 'lead_summary'],
  ['show me cold leads', 'lead_summary'],
  ['enquiry to conversion ratio', 'lead_summary'],
  ['how many deals in pipeline', 'lead_summary'],
  ['lead generation summary', 'lead_summary'],
  ['prospects at proposal stage', 'lead_summary'],
  ['count of dropped enquiries', 'lead_summary'],
  ['funnel stage distribution', 'lead_summary'],
  ['what leads are hot right now', 'lead_summary'],
  ['show potential deal value', 'lead_summary'],
  ['how many leads converted to orders', 'lead_summary'],
  ['lead source breakdown', 'lead_summary'],
  ['enquiry register', 'lead_summary'],
  ['opportunities we are chasing', 'lead_summary'],
  ['how many prospects contacted', 'lead_summary'],
  ['leads pending follow up today', 'lead_summary'],
  ['prospect pipeline health', 'lead_summary'],
  ['number of enquiries logged', 'lead_summary'],
  ['which stage has most leads', 'lead_summary'],

  // ── team_performance ──────────────────────────────────────────────────────
  ['which salesperson performs best', 'team_performance'],
  ['team performance report', 'team_performance'],
  ['who has the most leads', 'team_performance'],
  ['sales executive ranking', 'team_performance'],
  ['staff wise revenue', 'team_performance'],
  ['how is the team doing', 'team_performance'],
  ['employee performance summary', 'team_performance'],
  ['top rep by sales', 'team_performance'],
  ['who closed the most deals', 'team_performance'],
  ['salesperson leaderboard', 'team_performance'],
  ['revenue per employee', 'team_performance'],
  ['which executive is underperforming', 'team_performance'],
  ['team member statistics', 'team_performance'],
  ['user wise order count', 'team_performance'],
  ['staff productivity report', 'team_performance'],
  ['compare my sales people', 'team_performance'],
  ['which employee brought most business', 'team_performance'],
  ['sales staff comparison', 'team_performance'],
  ['executive wise performance numbers', 'team_performance'],
  ['who is my best sales rep', 'team_performance'],
  ['team leaderboard by revenue', 'team_performance'],
  ['salesman wise business figures', 'team_performance'],
  ['how are my executives performing', 'team_performance'],
  ['employee wise conversion rate', 'team_performance'],
  ['rank my team members', 'team_performance'],
  ['which staff member needs training', 'team_performance'],
  ['field officer performance', 'team_performance'],
  ['show me rep wise sales', 'team_performance'],
  ['who generated the highest revenue', 'team_performance'],
  ['team productivity metrics', 'team_performance'],
  ['individual performance breakdown', 'team_performance'],
  ['staff sales achievement report', 'team_performance'],
  ['which salesperson has lowest sales', 'team_performance'],
  ['team wise business summary', 'team_performance'],
  ['employee target achievement', 'team_performance'],
  ['sales team scorecard', 'team_performance'],
  ['who is lagging in the team', 'team_performance'],
  ['manager wise performance', 'team_performance'],
  ['show staff wise order numbers', 'team_performance'],

  // ── profit ────────────────────────────────────────────────────────────────
  ['what is our net profit', 'profit'],
  ['show profit margin', 'profit'],
  ['are we profitable', 'profit'],
  ['profit and loss summary', 'profit'],
  ['what is the bottomline', 'profit'],
  ['how much profit did we make', 'profit'],
  ['net margin percentage', 'profit'],
  ['profitability snapshot', 'profit'],
  ['income minus expenses', 'profit'],
  ['show me pnl', 'profit'],
  ['what is our earning after costs', 'profit'],
  ['are we making money or losing', 'profit'],
  ['gross profit figure', 'profit'],
  ['financial health summary', 'profit'],
  ['net income report', 'profit'],
  ['profit after deducting expenses', 'profit'],
  ['what margin are we running at', 'profit'],
  ['is the business in profit or loss', 'profit'],
  ['show profitability analysis', 'profit'],
  ['net earnings figure', 'profit'],
  ['profit percentage on sales', 'profit'],
  ['how profitable is the company', 'profit'],
  ['bottom line number', 'profit'],
  ['surplus after all costs', 'profit'],
  ['what is left after expenses', 'profit'],
  ['margin analysis report', 'profit'],
  ['profit loss statement', 'profit'],
  ['are we in the green', 'profit'],
  ['show net profitability', 'profit'],
  ['income versus expenditure summary', 'profit'],
  ['what is our operating profit', 'profit'],
  ['how much did we actually keep', 'profit'],
  ['profit trend snapshot', 'profit'],
  ['net gain or loss', 'profit'],
  ['margin on our business', 'profit'],
  ['profitability of the company', 'profit'],
  ['earnings after all deductions', 'profit'],
  ['show me the profit number', 'profit'],
  ['how much money did we actually make', 'profit'],
  ['what did we earn after expenses', 'profit'],
  ['how much money have we made overall', 'profit'],
  ['total earnings of the business', 'profit'],
  ['did we earn or lose money', 'profit'],
  ['money made after paying costs', 'profit'],
  ['what is our real earning', 'profit'],
  ['how much have we gained', 'profit'],
  ['net money retained', 'profit'],
  ['earning percentage on turnover', 'profit'],
  ['profit versus revenue comparison', 'profit'],
  ['what is our margin percentage', 'profit'],

  // ── outstanding ───────────────────────────────────────────────────────────
  ['show me unpaid invoices', 'outstanding'],
  ['how much money is pending from customers', 'outstanding'],
  ['outstanding receivables', 'outstanding'],
  ['who owes us money', 'outstanding'],
  ['overdue payments list', 'outstanding'],
  ['total amount to be recovered', 'outstanding'],
  ['which bills are unpaid', 'outstanding'],
  ['pending collections report', 'outstanding'],
  ['dues from parties', 'outstanding'],
  ['what payments are overdue', 'outstanding'],
  ['receivable amount summary', 'outstanding'],
  ['customers with pending dues', 'outstanding'],
  ['how much is yet to be collected', 'outstanding'],
  ['unsettled invoice amount', 'outstanding'],
  ['show debtors', 'outstanding'],
  ['which parties have not paid', 'outstanding'],
  ['total outstanding balance', 'outstanding'],
  ['pending payment from distributors', 'outstanding'],
  ['recovery pending amount', 'outstanding'],
  ['aged receivables report', 'outstanding'],
  ['who has not cleared their dues', 'outstanding'],
  ['money stuck with customers', 'outstanding'],
  ['list of defaulters', 'outstanding'],
  ['credit outstanding against parties', 'outstanding'],
  ['what is our receivable position', 'outstanding'],
  ['show pending bills to collect', 'outstanding'],
  ['overdue amount from dealers', 'outstanding'],
  ['collection pending summary', 'outstanding'],
  ['unpaid dues total', 'outstanding'],
  ['balance receivable from clients', 'outstanding'],
  ['which invoices crossed due date', 'outstanding'],
  ['payment recovery status', 'outstanding'],
  ['how much credit is outstanding', 'outstanding'],
  ['debtor ageing analysis', 'outstanding'],
  ['show me overdue accounts', 'outstanding'],
  ['pending realisation from market', 'outstanding'],
  ['what amount is stuck in receivables', 'outstanding'],
  ['party wise outstanding balance', 'outstanding'],

  // ── invoice_list ──────────────────────────────────────────────────────────
  ['show me all invoices', 'invoice_list'],
  ['list the bills raised', 'invoice_list'],
  ['how many invoices generated', 'invoice_list'],
  ['invoice summary report', 'invoice_list'],
  ['display billing records', 'invoice_list'],
  ['total invoiced amount', 'invoice_list'],
  ['give me invoice details', 'invoice_list'],
  ['what bills have been issued', 'invoice_list'],
  ['invoice count by status', 'invoice_list'],
  ['show billing history', 'invoice_list'],
  ['all bills raised this month', 'invoice_list'],
  ['invoice register', 'invoice_list'],
  ['paid invoices list', 'invoice_list'],
  ['how many bills did we cut', 'invoice_list'],
  ['show invoice book', 'invoice_list'],
  ['billing summary for the period', 'invoice_list'],
  ['list all tax invoices', 'invoice_list'],
  ['invoices issued to customers', 'invoice_list'],
  ['what is total billing value', 'invoice_list'],
  ['show me the bills we raised', 'invoice_list'],
  ['invoice records with amounts', 'invoice_list'],
  ['how many bills are paid', 'invoice_list'],
  ['gst invoice listing', 'invoice_list'],
  ['billing document list', 'invoice_list'],
  ['show invoices with their status', 'invoice_list'],
  ['total number of bills', 'invoice_list'],
  ['invoice wise breakup', 'invoice_list'],
  ['display all billing entries', 'invoice_list'],
  ['what invoices exist in the system', 'invoice_list'],
  ['bill register report', 'invoice_list'],
  ['show recent invoices raised', 'invoice_list'],
  ['invoice value summary', 'invoice_list'],
  ['all billing transactions', 'invoice_list'],
  ['how many invoices are settled', 'invoice_list'],
  ['list bills by customer', 'invoice_list'],

  // ── expense_breakdown ─────────────────────────────────────────────────────
  ['what are our total expenses', 'expense_breakdown'],
  ['expense breakdown by category', 'expense_breakdown'],
  ['how much did we spend', 'expense_breakdown'],
  ['show me the cost summary', 'expense_breakdown'],
  ['where is our money going', 'expense_breakdown'],
  ['biggest spending categories', 'expense_breakdown'],
  ['total expenditure this month', 'expense_breakdown'],
  ['list all costs incurred', 'expense_breakdown'],
  ['overhead summary', 'expense_breakdown'],
  ['category wise expense report', 'expense_breakdown'],
  ['how much outflow so far', 'expense_breakdown'],
  ['spending analysis', 'expense_breakdown'],
  ['what did we spend on logistics', 'expense_breakdown'],
  ['cost centre breakdown', 'expense_breakdown'],
  ['show expenditure details', 'expense_breakdown'],
  ['which category costs us most', 'expense_breakdown'],
  ['total cost incurred', 'expense_breakdown'],
  ['expense report summary', 'expense_breakdown'],
  ['how much was spent on travel', 'expense_breakdown'],
  ['operational cost breakup', 'expense_breakdown'],
  ['show me all expenses logged', 'expense_breakdown'],
  ['what are our overheads', 'expense_breakdown'],
  ['expenditure by head', 'expense_breakdown'],
  ['money spent this quarter', 'expense_breakdown'],
  ['cost analysis report', 'expense_breakdown'],
  ['show spending by category', 'expense_breakdown'],
  ['total outgoings summary', 'expense_breakdown'],
  ['expense heads and amounts', 'expense_breakdown'],
  ['what is our burn', 'expense_breakdown'],
  ['highest expense category', 'expense_breakdown'],
  ['break up of costs', 'expense_breakdown'],
  ['show marketing spend', 'expense_breakdown'],
  ['salary and other expenses', 'expense_breakdown'],
  ['expenditure summary report', 'expense_breakdown'],
  ['how much cost did we book', 'expense_breakdown'],
  ['expense wise distribution', 'expense_breakdown'],

  // ── stock_level ───────────────────────────────────────────────────────────
  ['what is our current stock', 'stock_level'],
  ['show inventory levels', 'stock_level'],
  ['how many units do we have in warehouse', 'stock_level'],
  ['stock on hand report', 'stock_level'],
  ['inventory summary', 'stock_level'],
  ['available quantity of goods', 'stock_level'],
  ['what is the stock value', 'stock_level'],
  ['display warehouse holdings', 'stock_level'],
  ['how much inventory is reserved', 'stock_level'],
  ['current qty in godown', 'stock_level'],
  ['stock position', 'stock_level'],
  ['tell me inventory count', 'stock_level'],
  ['how much stock is available to sell', 'stock_level'],
  ['what quantity is lying in stock', 'stock_level'],
  ['inventory holding value', 'stock_level'],
  ['show me stock balance', 'stock_level'],
  ['how many pieces in godown', 'stock_level'],
  ['current inventory status', 'stock_level'],
  ['warehouse stock report', 'stock_level'],
  ['what do we have in store', 'stock_level'],
  ['available inventory quantity', 'stock_level'],
  ['stock ledger balance', 'stock_level'],
  ['free stock available', 'stock_level'],
  ['show closing stock', 'stock_level'],
  ['how much material is in hand', 'stock_level'],
  ['inventory valuation report', 'stock_level'],
  ['stock in hand summary', 'stock_level'],
  ['what is lying in the warehouse', 'stock_level'],
  ['total units held in inventory', 'stock_level'],
  ['show me batch wise stock', 'stock_level'],
  ['unreserved stock quantity', 'stock_level'],
  ['physical stock position', 'stock_level'],
  ['how much goods do we hold', 'stock_level'],
  ['inventory count by product', 'stock_level'],

  // ── low_stock ─────────────────────────────────────────────────────────────
  ['which products are running low', 'low_stock'],
  ['show low stock items', 'low_stock'],
  ['what will stock out soon', 'low_stock'],
  ['reorder alert list', 'low_stock'],
  ['products about to finish', 'low_stock'],
  ['stock shortage warning', 'low_stock'],
  ['which items need replenishment', 'low_stock'],
  ['inventory running short', 'low_stock'],
  ['what should i reorder', 'low_stock'],
  ['items at risk of stockout', 'low_stock'],
  ['low inventory report', 'low_stock'],
  ['which goods are almost empty', 'low_stock'],
  ['critical stock levels', 'low_stock'],
  ['what is below reorder point', 'low_stock'],
  ['show shortage list', 'low_stock'],
  ['products needing urgent purchase', 'low_stock'],
  ['which sku will run out first', 'low_stock'],
  ['stock replenishment required', 'low_stock'],
  ['items falling below minimum level', 'low_stock'],
  ['show me depleting products', 'low_stock'],
  ['what needs immediate restocking', 'low_stock'],
  ['near zero stock items', 'low_stock'],
  ['urgent purchase requirement list', 'low_stock'],
  ['which products will finish this week', 'low_stock'],
  ['stock running out alert', 'low_stock'],
  ['reorder level breach report', 'low_stock'],
  ['what inventory is insufficient', 'low_stock'],
  ['show items to purchase urgently', 'low_stock'],
  ['danger level stock items', 'low_stock'],
  ['which goods need refilling', 'low_stock'],
  ['products with dangerously low quantity', 'low_stock'],
  ['restocking priority list', 'low_stock'],
  ['what will be out of stock soon', 'low_stock'],
  ['minimum stock alert', 'low_stock'],

  // ── dead_stock ────────────────────────────────────────────────────────────
  ['show me dead stock', 'dead_stock'],
  ['which products are not selling', 'dead_stock'],
  ['slow moving inventory', 'dead_stock'],
  ['stagnant stock report', 'dead_stock'],
  ['unsold goods sitting in warehouse', 'dead_stock'],
  ['what inventory is stuck', 'dead_stock'],
  ['non moving items list', 'dead_stock'],
  ['products with zero sales', 'dead_stock'],
  ['stale inventory analysis', 'dead_stock'],
  ['where is capital locked in stock', 'dead_stock'],
  ['identify obsolete stock', 'dead_stock'],
  ['which goods have not moved', 'dead_stock'],
  ['idle inventory report', 'dead_stock'],
  ['products lying unsold for months', 'dead_stock'],
  ['show me non performing sku', 'dead_stock'],
  ['what stock is gathering dust', 'dead_stock'],
  ['items with no sales activity', 'dead_stock'],
  ['blocked working capital in inventory', 'dead_stock'],
  ['which products should we discount', 'dead_stock'],
  ['inventory that never sells', 'dead_stock'],
  ['dead inventory value', 'dead_stock'],
  ['slow movers in the warehouse', 'dead_stock'],
  ['show unsold stock items', 'dead_stock'],
  ['what goods are not rotating', 'dead_stock'],
  ['products with no offtake', 'dead_stock'],
  ['stuck inventory analysis', 'dead_stock'],
  ['zero movement stock list', 'dead_stock'],
  ['which items are wasting shelf space', 'dead_stock'],
  ['obsolete goods report', 'dead_stock'],
  ['inventory ageing dead items', 'dead_stock'],
  ['what should we liquidate', 'dead_stock'],
  ['non selling product list', 'dead_stock'],
  ['which products had no sales at all', 'dead_stock'],
  ['unsold items lying for long time', 'dead_stock'],
  ['stagnant goods report', 'dead_stock'],
  ['obsolete inventory listing', 'dead_stock'],
  ['products nobody is buying', 'dead_stock'],
  ['items with zero offtake', 'dead_stock'],
  ['show slow moving goods', 'dead_stock'],
  ['non moving stock analysis', 'dead_stock'],
  ['which sku has no movement', 'dead_stock'],
  ['unsold merchandise report', 'dead_stock'],
  ['idle goods in warehouse', 'dead_stock'],

  // ── forecast ──────────────────────────────────────────────────────────────
  ['forecast demand for next month', 'forecast'],
  ['predict future sales', 'forecast'],
  ['what will we sell next month', 'forecast'],
  ['demand projection report', 'forecast'],
  ['expected sales volume ahead', 'forecast'],
  ['sales prediction by product', 'forecast'],
  ['how much should we produce next month', 'forecast'],
  ['upcoming demand estimate', 'forecast'],
  ['project the sales trend', 'forecast'],
  ['what is expected demand', 'forecast'],
  ['future requirement planning', 'forecast'],
  ['forecast units needed', 'forecast'],
  ['next month projection', 'forecast'],
  ['estimate coming month sales', 'forecast'],
  ['what quantity should we manufacture', 'forecast'],
  ['demand planning figures', 'forecast'],
  ['predicted offtake for next period', 'forecast'],
  ['sales outlook for coming weeks', 'forecast'],
  ['how much stock will we need', 'forecast'],
  ['anticipated demand by item', 'forecast'],
  ['projection of future orders', 'forecast'],
  ['what does the trend suggest ahead', 'forecast'],
  ['production planning estimate', 'forecast'],
  ['expected requirement next quarter', 'forecast'],
  ['forecast sales for each product', 'forecast'],
  ['predict how much we will sell', 'forecast'],
  ['future sales estimate report', 'forecast'],
  ['demand forecast summary', 'forecast'],
  ['what will demand look like', 'forecast'],
  ['projected volumes ahead', 'forecast'],
  ['estimate upcoming requirement', 'forecast'],
  ['forward looking sales plan', 'forecast'],

  // ── churn ─────────────────────────────────────────────────────────────────
  ['which distributors are at churn risk', 'churn'],
  ['who might stop ordering', 'churn'],
  ['inactive channel partners', 'churn'],
  ['dormant distributor list', 'churn'],
  ['retention risk analysis', 'churn'],
  ['which dealers have gone quiet', 'churn'],
  ['partners we might lose', 'churn'],
  ['distributor engagement report', 'churn'],
  ['who has not ordered recently', 'churn'],
  ['show disengaged accounts', 'churn'],
  ['channel partner risk assessment', 'churn'],
  ['which distributors are declining', 'churn'],
  ['at risk distributor accounts', 'churn'],
  ['who stopped buying from us', 'churn'],
  ['distributors going inactive', 'churn'],
  ['show me churning partners', 'churn'],
  ['which dealers reduced their orders', 'churn'],
  ['attrition risk among distributors', 'churn'],
  ['partners with falling purchase trend', 'churn'],
  ['who needs urgent relationship attention', 'churn'],
  ['sleeping distributor accounts', 'churn'],
  ['which channel partners are slipping', 'churn'],
  ['distributor retention report', 'churn'],
  ['accounts we are likely to lose', 'churn'],
  ['show me dormant dealers', 'churn'],
  ['which partners have reduced their activity', 'churn'],
  ['customer churn prediction', 'churn'],
  ['distributors not buying anymore', 'churn'],
  ['flag risky partner accounts', 'churn'],
  ['who is drifting away from us', 'churn'],
  ['loyalty risk among dealers', 'churn'],
  ['which distributors need winback', 'churn'],

  // ── customer_lookup ───────────────────────────────────────────────────────
  ['who are our top customers', 'customer_lookup'],
  ['show me customer details', 'customer_lookup'],
  ['best clients by value', 'customer_lookup'],
  ['customer lifetime value ranking', 'customer_lookup'],
  ['which buyer spends the most', 'customer_lookup'],
  ['list our accounts', 'customer_lookup'],
  ['client purchase history', 'customer_lookup'],
  ['most valuable buyers', 'customer_lookup'],
  ['customer wise business summary', 'customer_lookup'],
  ['tell me about this party', 'customer_lookup'],
  ['top buyers report', 'customer_lookup'],
  ['who is our biggest client', 'customer_lookup'],
  ['customer wise sales figures', 'customer_lookup'],
  ['show buyer details and history', 'customer_lookup'],
  ['which client gives most orders', 'customer_lookup'],
  ['party wise business report', 'customer_lookup'],
  ['customer profile information', 'customer_lookup'],
  ['show me client rankings', 'customer_lookup'],
  ['who buys the most from us', 'customer_lookup'],
  ['account wise purchase summary', 'customer_lookup'],
  ['customer order history details', 'customer_lookup'],
  ['key accounts list', 'customer_lookup'],
  ['which customers are most loyal', 'customer_lookup'],
  ['buyer wise revenue contribution', 'customer_lookup'],
  ['show customer master details', 'customer_lookup'],
  ['important clients report', 'customer_lookup'],
  ['who are our premium buyers', 'customer_lookup'],
  ['customer transaction summary', 'customer_lookup'],
  ['show me party ledger details', 'customer_lookup'],
  ['top accounts by purchase value', 'customer_lookup'],
  ['client wise order count', 'customer_lookup'],
  ['customer segmentation by value', 'customer_lookup'],

  // ── help ──────────────────────────────────────────────────────────────────
  ['help', 'help'],
  ['what can you do', 'help'],
  ['hello', 'help'],
  ['hi there', 'help'],
  ['how do i use this', 'help'],
  ['show me your capabilities', 'help'],
  ['what questions can i ask', 'help'],
  ['guide me', 'help'],
  ['assist me please', 'help'],
  ['hey', 'help'],
  ['what are you able to answer', 'help'],
  ['give me some examples', 'help'],
  ['hi', 'help'],
  ['who are you', 'help'],
  ['what is prism', 'help'],
  ['explain what you do', 'help'],
  ['list your features', 'help'],
  ['how does this assistant work', 'help'],
  ['i need help using you', 'help'],
  ['what topics do you cover', 'help'],
  ['show command list', 'help'],
  ['good morning', 'help'],
  ['can you help me', 'help'],
  ['what should i ask you', 'help'],
  ['instructions please', 'help'],
  ['tell me your functions', 'help'],
  ['what all can you tell me', 'help'],
  ['start', 'help'],
  ['options available', 'help'],
  ['how to begin', 'help'],
  ['good evening', 'help'],
  ['good afternoon', 'help'],
  ['namaste', 'help'],
  ['hey there', 'help'],
  ['hello there', 'help'],
  ['are you there', 'help'],
  ['help me', 'help'],
  ['menu', 'help'],
  ['what next', 'help'],
  ['thanks', 'help'],
  ['thank you', 'help'],
  ['ok thanks', 'help'],
  ['support', 'help'],
  ['i am new here', 'help'],
  ['show me around', 'help'],
  ['what do you know', 'help'],
  ['introduce yourself', 'help'],
  ['how can you assist', 'help'],
  ['tell me what you can answer', 'help'],
  ['give me a tour', 'help'],
];

export const INTENT_LABELS = [...new Set(TRAINING_DATA.map(([, y]) => y))].sort();
